version: '3.8'

services:
  testclient:
    build:
      context: ./TestClient
      dockerfile: Dockerfile
    container_name: testclient
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - sockettest-network
    depends_on:
      - server-v4-fast
      - server-v4-slow
      - server-v6-fast
      - server-v6-slow
    environment:
      - HOST_A=${HOST_A}
      - HOST_B=${HOST_B}
      - V4_FAST=${V4_FAST}
      - V4_SLOW=${V4_SLOW}
      - V6_FAST=${V6_FAST}
      - V6_SLOW=${V6_SLOW}
    stdin_open: true
    tty: true

  server-v4-fast:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: server-v4-fast
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${V4_FAST}
      - DELAY=${V4_FAST_DELAY}
    networks:
      sockettest-network:
        ipv4_address: ${V4_FAST}
    stdin_open: true
    tty: true

  server-v4-slow:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: server-v4-slow
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${V4_SLOW}
      - DELAY=${V4_SLOW_DELAY}
    networks:
      sockettest-network:
        ipv4_address: ${V4_SLOW}
    stdin_open: true
    tty: true

  server-v6-fast:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: server-v6-fast
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${V6_FAST}
      - DELAY=${V6_FAST_DELAY}
    networks:
      sockettest-network:
        ipv6_address: ${V6_FAST}
    stdin_open: true
    tty: true

  server-v6-slow:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: server-v6-slow
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${V6_SLOW}
      - DELAY=${V6_SLOW_DELAY}
    networks:
      sockettest-network:
        ipv6_address: ${V6_SLOW}
    stdin_open: true
    tty: true

networks:
  sockettest-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${IPV4_SUBNET}
          gateway: ${IPV4_GATEWAY}
        - subnet: ${IPV6_SUBNET}
          gateway: ${IPV6_GATEWAY}
