version: '3.8'

services:
  testclient:
    build:
      context: ./TestClient
      dockerfile: Dockerfile
    container_name: testclient
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - sockettest-network
    depends_on:
      - testserver1
      - testserver2
      - testserver3
      - testserver4
    environment:
      - SERVER1_IP=${SERVER1_IP}
      - SERVER2_IP=${SERVER2_IP}
      - SERVER3_IP=${SERVER3_IP}
      - SERVER4_IP=${SERVER4_IP}
    stdin_open: true
    tty: true

  testserver1:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: testserver1
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${SERVER1_IP}
      - DELAY=${DELAY1}
    ports:
      - "5001:5000"
    networks:
      sockettest-network:
        ipv4_address: ${SERVER1_IP}
    stdin_open: true
    tty: true

  testserver2:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: testserver2
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${SERVER2_IP}
      - DELAY=${DELAY2}
    ports:
      - "5002:5000"
    networks:
      sockettest-network:
        ipv4_address: ${SERVER2_IP}
    stdin_open: true
    tty: true

  testserver3:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: testserver3
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${SERVER3_IP}
      - DELAY=${DELAY3}
    ports:
      - "5003:5000"
    networks:
      sockettest-network:
        ipv6_address: ${SERVER3_IP}
    stdin_open: true
    tty: true

  testserver4:
    build:
      context: ./TestServer
      dockerfile: Dockerfile
    container_name: testserver4
    cap_add:
      - NET_ADMIN
    environment:
      - CONTAINER_IP=${SERVER4_IP}
      - DELAY=${DELAY4}
    ports:
      - "5004:5000"
    networks:
      sockettest-network:
        ipv6_address: ${SERVER4_IP}
    stdin_open: true
    tty: true

networks:
  sockettest-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${IPV4_SUBNET}
          gateway: ${IPV4_GATEWAY}
        - subnet: ${IPV6_SUBNET}
          gateway: ${IPV6_GATEWAY}
