#!/bin/bash
### BEGIN INIT INFO
# Provides:          coredns
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CoreDNS DNS server
# Description:       CoreDNS DNS server
### END INIT INFO

DAEMON="/usr/local/bin/coredns"
DAEMON_OPTS="-conf /etc/coredns/Corefile"
PIDFILE="/var/run/coredns.pid"

case "$1" in
  start)
    echo "Starting CoreDNS..."
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS
    ;;
  stop)
    echo "Stopping CoreDNS..."
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
      echo "CoreDNS is running (PID: $(cat $PIDFILE))"
    else
      echo "CoreDNS is not running"
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
